sudo apt-get update ; sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev

sudo apt-get install libgdbm-dev libncurses5-dev automake libtool bison libffi-dev ; curl -L https://get.rvm.io | bash -s stable ; source ~/.rvm/scripts/rvm ; rvm install 2.3.0 ; rvm use 2.3.0 --default ; ruby -v

gem install bundler

curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash - ; sudo apt-get install -y nodejs
